### ISSUE TITLE
tensorflow-gpu forward compatibility

### ISSUE THREAD

**Issue by YuzhouMao** [voxel51/eta#166]
I have Ubuntu-16.04 with CUDA-9.0. I installed eta following the documentation. While testing the installation using 

`python embed_image.py`

I had the following error:

> Traceback (most recent call last):
  File "/home/yuzhou/Developer/Pyenvs/eta3/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py", line 41, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/yuzhou/Developer/Pyenvs/eta3/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/yuzhou/Developer/Pyenvs/eta3/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/home/yuzhou/Developer/Pyenvs/eta3/lib/python3.5/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/home/yuzhou/Developer/Pyenvs/eta3/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libcusolver.so.8.0: cannot open shared object file: No such file or directory

> During handling of the above exception, another exception occurred:

> Traceback (most recent call last):
  File "embed_image.py", line 32, in <module>
    import tensorflow as tf
  File "/home/yuzhou/Developer/Pyenvs/eta3/lib/python3.5/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/home/yuzhou/Developer/Pyenvs/eta3/lib/python3.5/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/yuzhou/Developer/Pyenvs/eta3/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py", line 52, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/home/yuzhou/Developer/Pyenvs/eta3/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py", line 41, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/yuzhou/Developer/Pyenvs/eta3/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/yuzhou/Developer/Pyenvs/eta3/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/home/yuzhou/Developer/Pyenvs/eta3/lib/python3.5/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/home/yuzhou/Developer/Pyenvs/eta3/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libcusolver.so.8.0: cannot open shared object file: No such file or directory`

It turns out that since I only have CUDA-9.0, there is no libcusolver.so.8.0 in '/usr/local/cuda'. Instead, I have libcusolver.so.9.0. After upgrading tensorflow-gpu to the latest version, the error was resolved.

**Comment by brimoor** [comment]
@YuzhouMao thanks for bringing this to our attention. I updated the installation script to install the latest version of `tensorflow-gpu` if CUDA 9.X is installed and revert to `tensorflow-gpu 1.4` if CUDA 8.X is installed.

According to https://www.tensorflow.org/install/install_sources#tested_source_configurations, 1.4 is the last `tensorflow-gpu` version to support CUDA 8.

Can you pull the latest `develop` branch and confirm that the install script works for you?

**Comment by YuzhouMao** [comment]
Sure. I pulled the latest branch just now and it works.
