### ISSUE TITLE
TypeError in Models with Python 2.7

### ISSUE THREAD

**Issue by tylerganter** [voxel51/eta#182]
Using Python 2.7.10 I get the following error when running

$python embed_image.py

Uncaught exception
Traceback (most recent call last):
  File "embed_image.py", line 76, in <module>
    embed_image(impath)
  File "embed_image.py", line 54, in embed_image
    with VGG16Featurizer() as vfeaturizer:
  File "/Users/tylerganter/theta/eta/eta/core/features.py", line 93, in __enter__
    self.start()
  File "/Users/tylerganter/theta/eta/eta/core/features.py", line 127, in start
    self._start()
  File "/Users/tylerganter/theta/eta/eta/core/vgg16.py", line 478, in _start
    self.vgg16 = VGG16(self.config)
  File "/Users/tylerganter/theta/eta/eta/core/vgg16.py", line 91, in __init__
    self._load_model(self.config.model)
  File "/Users/tylerganter/theta/eta/eta/core/vgg16.py", line 452, in _load_model
    weights = etam.NpzModelWeights(model).load()
  File "/Users/tylerganter/theta/eta/eta/core/models.py", line 920, in load
    return self._load()
  File "/Users/tylerganter/theta/eta/eta/core/models.py", line 940, in _load
    self.update(np.load(self.model_path))
  File "/Users/tylerganter/envs/eta2/lib/python2.7/site-packages/numpy/lib/npyio.py", line 415, in load
    fid = open(os_fspath(file), "rb")
  File "/Users/tylerganter/envs/eta2/lib/python2.7/site-packages/numpy/compat/py3k.py", line 237, in os_fspath
    "not " + path_type.__name__)
TypeError: expected str, bytes or os.PathLike object, not unicode

**Comment by tylerganter** [comment]
Issue was resolved with modification to the requirements.txt file
